catalog:
  react: 19.1.0
  react-dom: 19.1.0

catalogs:
  example-react-types:
    '@types/react': ~19.1.0
    '@types/react-dom': ~19.1.0
  package-react-types:
    '@types/react': ^17
    '@types/react-dom': ^17

checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

initScope: stream-io

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs
