catalog:
  "@types/react": ~18.3.27
  "@types/react-dom": ~18.3.7
  react: ~18.3.1
  react-dom: ~18.3.1

checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

initScope: stream-io

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs
