catalog:
  "@types/react": ~19.1.0
  "@types/react-dom": 19.1.0
  react: 19.1.0
  react-dom: 19.1.0

checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

initScope: stream-io

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs
