name: Version and Release

on:
  workflow_dispatch:

concurrency:
  group: version-and-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-and-release:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint Packages
        run: yarn lint:libs

      - name: Build packages
        run: NODE_ENV=production yarn build:libs

      - name: Test packages
#        run: yarn test:ci:libs
        run: echo "Tests not run; uncomment the line above to fix this."

      - name: Configure Yarn and Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          yarn config set npmRegistryServer https://registry.npmjs.org/
          yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}

      - name: Version Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          yarn version

      - name: Publish Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run:
#          yarn publish --tag "alpha"
        run:
          echo "Publish stub called, will not publish."
